MAPA_ATIVOS = {
    'AZTE.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'BRAV.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'CSAN.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'RPMG.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'PETR.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'RECV.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'PRIO.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'RAIZ.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'UGPA.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'VBBR.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'LUPA.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'OPCT.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'OSXB.SA': {'setor': 'Petróleo, Gás e Biocombustíveis'},
    'AURA.SA': {'setor': 'Mineração'},
    'BRAP.SA': {'setor': 'Mineração'},
    'CBAV.SA': {'setor': 'Mineração'},
    'CMIN.SA': {'setor': 'Mineração'},
    'LTEL.SA': {'setor': 'Mineração'},
    'LTLA.SA': {'setor': 'Mineração'},
    'VALE.SA': {'setor': 'Mineração'},
    'FESA.SA': {'setor': 'Siderurgia e Metalurgia'},
    'GGBR.SA': {'setor': 'Siderurgia e Metalurgia'},
    'GOAU.SA': {'setor': 'Siderurgia e Metalurgia'},
    'CSNA.SA': {'setor': 'Siderurgia e Metalurgia'},
    'USIM.SA': {'setor': 'Siderurgia e Metalurgia'},
    'MGEL.SA': {'setor': 'Siderurgia e Metalurgia'},
    'PATI.SA': {'setor': 'Siderurgia e Metalurgia'},
    'TKNO.SA': {'setor': 'Siderurgia e Metalurgia'},
    'PMAM.SA': {'setor': 'Siderurgia e Metalurgia'},
    'BRKM.SA': {'setor': 'Químicos'},
    'DEXP.SA': {'setor': 'Químicos'},
    'FHER.SA': {'setor': 'Químicos'},
    'NUTR.SA': {'setor': 'Químicos'},
    'VITT.SA': {'setor': 'Químicos'},
    'CRPG.SA': {'setor': 'Químicos'},
    'UNIP.SA': {'setor': 'Químicos'},
    'DXCO.SA': {'setor': 'Madeira e Papel'},
    'EUCA.SA': {'setor': 'Madeira e Papel'},
    'KLBN.SA': {'setor': 'Madeira e Papel'},
    'MSPA.SA': {'setor': 'Madeira e Papel'},
    'NEMO.SA': {'setor': 'Madeira e Papel'},
    'SUZB.SA': {'setor': 'Madeira e Papel'},
    'RANI.SA': {'setor': 'Embalagens'},
    'SNSY.SA': {'setor': 'Materiais Diversos'},
    'ETER.SA': {'setor': 'Construção e Engenharia'},
    'HAGA.SA': {'setor': 'Construção e Engenharia'},
    'PTBL.SA': {'setor': 'Construção e Engenharia'},
    'AZEV.SA': {'setor': 'Construção e Engenharia'},
    'SOND.SA': {'setor': 'Construção e Engenharia'},
    'EMBR.SA': {'setor': 'Material de Transporte'},
    'FRAS.SA': {'setor': 'Material de Transporte'},
    'POMO.SA': {'setor': 'Material de Transporte'},
    'RAPT.SA': {'setor': 'Material de Transporte'},
    'RCSL.SA': {'setor': 'Material de Transporte'},
    'RSUL.SA': {'setor': 'Material de Transporte'},
    'TUPY.SA': {'setor': 'Material de Transporte'},
    'MWET.SA': {'setor': 'Material de Transporte'},
    'SHUL.SA': {'setor': 'Máquinas e Equipamentos'},
    'WEGE.SA': {'setor': 'Máquinas e Equipamentos'},
    'EALT.SA': {'setor': 'Máquinas e Equipamentos'},
    'AERI.SA': {'setor': 'Máquinas e Equipamentos'},
    'ARML.SA': {'setor': 'Máquinas e Equipamentos'},
    'BDLL.SA': {'setor': 'Máquinas e Equipamentos'},
    'INEP.SA': {'setor': 'Máquinas e Equipamentos'},
    'KEPL.SA': {'setor': 'Máquinas e Equipamentos'},
    'FRIO.SA': {'setor': 'Máquinas e Equipamentos'},
    'MILS.SA': {'setor': 'Máquinas e Equipamentos'},
    'NORD.SA': {'setor': 'Máquinas e Equipamentos'},
    'PTCA.SA': {'setor': 'Máquinas e Equipamentos'},
    'ROMI.SA': {'setor': 'Máquinas e Equipamentos'},
    'MTSA.SA': {'setor': 'Máquinas e Equipamentos'},
    'TASA.SA': {'setor': 'Máquinas e Equipamentos'},
    'AZUL.SA': {'setor': 'Transporte'},
    'GOLL.SA': {'setor': 'Transporte'},
    'FRRN.SA': {'setor': 'Transporte'},
    'VSPT.SA': {'setor': 'Transporte'},
    'MRSA.SA': {'setor': 'Transporte'},
    'RAIL.SA': {'setor': 'Transporte'},
    'HBSA.SA': {'setor': 'Transporte'},
    'LOGN.SA': {'setor': 'Transporte'},
    'LUXM.SA': {'setor': 'Transporte'},
    'JSLG.SA': {'setor': 'Transporte'},
    'TGMA.SA': {'setor': 'Transporte'},
    'CRTE.SA': {'setor': 'Transporte'},
    'ECOR.SA': {'setor': 'Transporte'},
    'MOTV.SA': {'setor': 'Transporte'},
    'TPIS.SA': {'setor': 'Transporte'},
    'AGRU.SA': {'setor': 'Transporte'},
    'HMOB.SA': {'setor': 'Transporte'},
    'IVPR.SA': {'setor': 'Transporte'},
    'PSVM.SA': {'setor': 'Transporte'},
    'STBP.SA': {'setor': 'Transporte'},
    'PORT.SA': {'setor': 'Transporte'},
    'BBML.SA': {'setor': 'Serviços'},
    'CTAX.SA': {'setor': 'Serviços'},
    'DTCY.SA': {'setor': 'Serviços'},
    'ALPK.SA': {'setor': 'Serviços'},
    'GGPS.SA': {'setor': 'Serviços'},
    'PRNR.SA': {'setor': 'Serviços'},
    'SEQL.SA': {'setor': 'Serviços'},
    'VLID.SA': {'setor': 'Serviços'},
    'EPAR.SA': {'setor': 'Comércio Varejista'},
    'MMAQ.SA': {'setor': 'Comércio Varejista'},
    'RBNS.SA': {'setor': 'Comércio Varejista'},
    'WLMM.SA': {'setor': 'Comércio Varejista'},
    'TTEN.SA': {'setor': 'Agropecuária'},
    'GRAO.SA': {'setor': 'Agropecuária'},
    'AGXY.SA': {'setor': 'Agropecuária'},
    'APTI.SA': {'setor': 'Agropecuária'},
    'SOJA.SA': {'setor': 'Agropecuária'},
    'AGRO.SA': {'setor': 'Agropecuária'},
    'CTCA.SA': {'setor': 'Agropecuária'},
    'EGGY.SA': {'setor': 'Agropecuária'},
    'SLCE.SA': {'setor': 'Agropecuária'},
    'LAND.SA': {'setor': 'Agropecuária'},
    'JALL.SA': {'setor': 'Alimentos Processados'},
    'SMTO.SA': {'setor': 'Alimentos Processados'},
    'BRFS.SA': {'setor': 'Alimentos Processados'},
    'BAUH.SA': {'setor': 'Alimentos Processados'},
    'JBSS.SA': {'setor': 'Alimentos Processados'},
    'MRFG.SA': {'setor': 'Alimentos Processados'},
    'BEEF.SA': {'setor': 'Alimentos Processados'},
    'MNPR.SA': {'setor': 'Alimentos Processados'},
    'CAML.SA': {'setor': 'Alimentos Processados'},
    'JOPA.SA': {'setor': 'Alimentos Processados'},
    'MDIA.SA': {'setor': 'Alimentos Processados'},
    'ODER.SA': {'setor': 'Alimentos Processados'},
    'ABEV.SA': {'setor': 'Bebidas'},
    'NATU.SA': {'setor': 'Produtos de Cuidado Pessoal e de Limpeza'},
    'BOBR.SA': {'setor': 'Produtos de Cuidado Pessoal e de Limpeza'},
    'ASAI.SA': {'setor': 'Comércio e Distribuição'},
    'GMAT.SA': {'setor': 'Comércio e Distribuição'},
    'PCAR.SA': {'setor': 'Comércio e Distribuição'},
    'AZZA.SA': {'setor': 'Comércio Varejista'},
    'CEAB.SA': {'setor': 'Comércio Varejista'},
    'CGRA.SA': {'setor': 'Comércio Varejista'},
    'GUAR.SA': {'setor': 'Comércio Varejista'},
    'AMAR.SA': {'setor': 'Comércio Varejista'},
    'LREN.SA': {'setor': 'Comércio Varejista'},
    'VSTE.SA': {'setor': 'Comércio Varejista'},
    'ALLD.SA': {'setor': 'Comércio Varejista'},
    'BHIA.SA': {'setor': 'Comércio Varejista'},
    'MGLU.SA': {'setor': 'Comércio Varejista'},
    'AMER.SA': {'setor': 'Comércio Varejista'},
    'ESPA.SA': {'setor': 'Comércio Varejista'},
    'SBFG.SA': {'setor': 'Comércio Varejista'},
    'LLBI.SA': {'setor': 'Comércio Varejista'},
    'PETZ.SA': {'setor': 'Comércio Varejista'},
    'LJQQ.SA': {'setor': 'Comércio Varejista'},
    'AVLL.SA': {'setor': 'Construção Civil'},
    'CALI.SA': {'setor': 'Construção Civil'},
    'CURY.SA': {'setor': 'Construção Civil'},
    'CYRE.SA': {'setor': 'Construção Civil'},
    'DIRR.SA': {'setor': 'Construção Civil'},
    'EVEN.SA': {'setor': 'Construção Civil'},
    'EZTC.SA': {'setor': 'Construção Civil'},
    'FIEI.SA': {'setor': 'Construção Civil'},
    'GFSA.SA': {'setor': 'Construção Civil'},
    'HBOR.SA': {'setor': 'Construção Civil'},
    'INNC.SA': {'setor': 'Construção Civil'},
    'JHSF.SA': {'setor': 'Construção Civil'},
    'JFEN.SA': {'setor': 'Construção Civil'},
    'KLAS.SA': {'setor': 'Construção Civil'},
    'LAVV.SA': {'setor': 'Construção Civil'},
    'MELK.SA': {'setor': 'Construção Civil'},
    'MTRE.SA': {'setor': 'Construção Civil'},
    'MDNE.SA': {'setor': 'Construção Civil'},
    'MRVE.SA': {'setor': 'Construção Civil'},
    'PDGR.SA': {'setor': 'Construção Civil'},
    'PLPL.SA': {'setor': 'Construção Civil'},
    'CCTY.SA': {'setor': 'Construção Civil'},
    'RDNI.SA': {'setor': 'Construção Civil'},
    'RSID.SA': {'setor': 'Construção Civil'},
    'TCSA.SA': {'setor': 'Construção Civil'},
    'TEGA.SA': {'setor': 'Construção Civil'},
    'TEND.SA': {'setor': 'Construção Civil'},
    'TRIS.SA': {'setor': 'Construção Civil'},
    'VIVR.SA': {'setor': 'Construção Civil'},
    'CEDO.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'CTNM.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'DOHL.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'CATA.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'CTKA.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'PTNT.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'CTSA.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'SGPS.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'TXRX.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'TFCO.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'ALPA.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'CAMB.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'GRND.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'VULC.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'MNDL.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'TECN.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'VIVA.SA': {'setor': 'Tecidos, Vestuário e Calçados'},
    'WHRL.SA': {'setor': 'Utilidades Domésticas'},
    'TOKY.SA': {'setor': 'Utilidades Domésticas'},
    'UCAS.SA': {'setor': 'Utilidades Domésticas'},
    'WEST.SA': {'setor': 'Utilidades Domésticas'},
    'HETA.SA': {'setor': 'Utilidades Domésticas'},
    'AMOB.SA': {'setor': 'Automóveis e Motocicletas'},
    'MYPK.SA': {'setor': 'Automóveis e Motocicletas'},
    'LEVE.SA': {'setor': 'Automóveis e Motocicletas'},
    'PLAS.SA': {'setor': 'Automóveis e Motocicletas'},
    'HOOT.SA': {'setor': 'Hoteis e Restaurantes'},
    'MEAL.SA': {'setor': 'Hoteis e Restaurantes'},
    'ZAMP.SA': {'setor': 'Hoteis e Restaurantes'},
    'BMKS.SA': {'setor': 'Viagens e Lazer'},
    'ESTR.SA': {'setor': 'Viagens e Lazer'},
    'RVEE.SA': {'setor': 'Viagens e Lazer'},
    'AHEB.SA': {'setor': 'Viagens e Lazer'},
    'SHOW.SA': {'setor': 'Viagens e Lazer'},
    'CVCB.SA': {'setor': 'Viagens e Lazer'},
    'SMFT.SA': {'setor': 'Viagens e Lazer'},
    'ANIM.SA': {'setor': 'Diversos'},
    'ATED.SA': {'setor': 'Diversos'},
    'BIED.SA': {'setor': 'Diversos'},
    'COGN.SA': {'setor': 'Diversos'},
    'CSED.SA': {'setor': 'Diversos'},
    'SEER.SA': {'setor': 'Diversos'},
    'VTRU.SA': {'setor': 'Diversos'},
    'YDUQ.SA': {'setor': 'Diversos'},
    'RENT.SA': {'setor': 'Diversos'},
    'MOVI.SA': {'setor': 'Diversos'},
    'VAMO.SA': {'setor': 'Diversos'},
    'DOTZ.SA': {'setor': 'Diversos'},
    'BIOM.SA': {'setor': 'Medicamentos e Outros Produtos'},
    'OFSA.SA': {'setor': 'Medicamentos e Outros Produtos'},
    'AALR.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'DASA.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'FLRY.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'HAPV.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'MATD.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'ODPV.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'ONCO.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'QUAL.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'RDOR.SA': {'setor': 'Serv.Méd.Hospit.,Análises e Diagnósticos'},
    'BALM.SA': {'setor': 'Equipamentos'},
    'LMED.SA': {'setor': 'Equipamentos'},
    'BLAU.SA': {'setor': 'Comércio e Distribuição'},
    'DMVF.SA': {'setor': 'Comércio e Distribuição'},
    'PNVL.SA': {'setor': 'Comércio e Distribuição'},
    'EUFA.SA': {'setor': 'Comércio e Distribuição'},
    'HYPE.SA': {'setor': 'Comércio e Distribuição'},
    'PGMN.SA': {'setor': 'Comércio e Distribuição'},
    'PFRM.SA': {'setor': 'Comércio e Distribuição'},
    'RADL.SA': {'setor': 'Comércio e Distribuição'},
    'VVEO.SA': {'setor': 'Comércio e Distribuição'},
    'INTB.SA': {'setor': 'Computadores e Equipamentos'},
    'MLAS.SA': {'setor': 'Computadores e Equipamentos'},
    'POSI.SA': {'setor': 'Computadores e Equipamentos'},
    'BMOB.SA': {'setor': 'Programas e Serviços'},
    'BRQB.SA': {'setor': 'Programas e Serviços'},
    'ENJU.SA': {'setor': 'Programas e Serviços'},
    'IFCM.SA': {'setor': 'Programas e Serviços'},
    'LWSA.SA': {'setor': 'Programas e Serviços'},
    'CASH.SA': {'setor': 'Programas e Serviços'},
    'NGRD.SA': {'setor': 'Programas e Serviços'},
    'PDTC.SA': {'setor': 'Programas e Serviços'},
    'QUSW.SA': {'setor': 'Programas e Serviços'},
    'REAG.SA': {'setor': 'Programas e Serviços'},
    'TRAD.SA': {'setor': 'Programas e Serviços'},
    'TOTS.SA': {'setor': 'Programas e Serviços'},
    'LVTC.SA': {'setor': 'Programas e Serviços'},
    'BRST.SA': {'setor': 'Telecomunicações'},
    'DESK.SA': {'setor': 'Telecomunicações'},
    'OIBR.SA': {'setor': 'Telecomunicações'},
    'TELB.SA': {'setor': 'Telecomunicações'},
    'VIVT.SA': {'setor': 'Telecomunicações'},
    'TIMS.SA': {'setor': 'Telecomunicações'},
    'FIQE.SA': {'setor': 'Telecomunicações'},
    'AESO.SA': {'setor': 'Energia Elétrica'},
    'AFLT.SA': {'setor': 'Energia Elétrica'},
    'ALUP.SA': {'setor': 'Energia Elétrica'},
    'CBEE.SA': {'setor': 'Energia Elétrica'},
    'AURE.SA': {'setor': 'Energia Elétrica'},
    'CEBR.SA': {'setor': 'Energia Elétrica'},
    'CEED.SA': {'setor': 'Energia Elétrica'},
    'CLSC.SA': {'setor': 'Energia Elétrica'},
    'GPAR.SA': {'setor': 'Energia Elétrica'},
    'CMIG.SA': {'setor': 'Energia Elétrica'},
    'CEEB.SA': {'setor': 'Energia Elétrica'},
    'COCE.SA': {'setor': 'Energia Elétrica'},
    'COMR.SA': {'setor': 'Energia Elétrica'},
    'CPLE.SA': {'setor': 'Energia Elétrica'},
    'CPFE.SA': {'setor': 'Energia Elétrica'},
    'EKTR.SA': {'setor': 'Energia Elétrica'},
    'ELET.SA': {'setor': 'Energia Elétrica'},
    'EMAE.SA': {'setor': 'Energia Elétrica'},
    'ENGI.SA': {'setor': 'Energia Elétrica'},
    'ENMT.SA': {'setor': 'Energia Elétrica'},
    'ENEV.SA': {'setor': 'Energia Elétrica'},
    'EGIE.SA': {'setor': 'Energia Elétrica'},
    'EQPA.SA': {'setor': 'Energia Elétrica'},
    'EQMA.SA': {'setor': 'Energia Elétrica'},
    'EQTL.SA': {'setor': 'Energia Elétrica'},
    'GEPA.SA': {'setor': 'Energia Elétrica'},
    'ISAE.SA': {'setor': 'Energia Elétrica'},
    'LIGH.SA': {'setor': 'Energia Elétrica'},
    'LIGT.SA': {'setor': 'Energia Elétrica'},
    'NEOE.SA': {'setor': 'Energia Elétrica'},
    'PRMN.SA': {'setor': 'Energia Elétrica'},
    'REDE.SA': {'setor': 'Energia Elétrica'},
    'RNEW.SA': {'setor': 'Energia Elétrica'},
    'SRNA.SA': {'setor': 'Energia Elétrica'},
    'TAEE.SA': {'setor': 'Energia Elétrica'},
    'AMBP.SA': {'setor': 'Água e Saneamento'},
    'CASN.SA': {'setor': 'Água e Saneamento'},
    'CSMG.SA': {'setor': 'Água e Saneamento'},
    'IGSN.SA': {'setor': 'Água e Saneamento'},
    'ORVR.SA': {'setor': 'Água e Saneamento'},
    'SBSP.SA': {'setor': 'Água e Saneamento'},
    'SAPR.SA': {'setor': 'Água e Saneamento'},
    'CEGR.SA': {'setor': 'Gás'},
    'CGAS.SA': {'setor': 'Gás'},
    'PASS.SA': {'setor': 'Gás'},
    'ABCB.SA': {'setor': 'Intermediários Financeiros'},
    'RPAD.SA': {'setor': 'Intermediários Financeiros'},
    'BAZA.SA': {'setor': 'Intermediários Financeiros'},
    'BMGB.SA': {'setor': 'Intermediários Financeiros'},
    'BPAN.SA': {'setor': 'Intermediários Financeiros'},
    'BGIP.SA': {'setor': 'Intermediários Financeiros'},
    'BEES.SA': {'setor': 'Intermediários Financeiros'},
    'BPAR.SA': {'setor': 'Intermediários Financeiros'},
    'BRSR.SA': {'setor': 'Intermediários Financeiros'},
    'BRBI.SA': {'setor': 'Intermediários Financeiros'},
    'BBDC.SA': {'setor': 'Intermediários Financeiros'},
    'BBAS.SA': {'setor': 'Intermediários Financeiros'},
    'BSLI.SA': {'setor': 'Intermediários Financeiros'},
    'BPAC.SA': {'setor': 'Intermediários Financeiros'},
    'INBR.SA': {'setor': 'Intermediários Financeiros'},
    'ITUB.SA': {'setor': 'Intermediários Financeiros'},
    'BMIN.SA': {'setor': 'Intermediários Financeiros'},
    'BMEB.SA': {'setor': 'Intermediários Financeiros'},
    'BNBR.SA': {'setor': 'Intermediários Financeiros'},
    'PINE.SA': {'setor': 'Intermediários Financeiros'},
    'SANB.SA': {'setor': 'Intermediários Financeiros'},
    'MERC.SA': {'setor': 'Intermediários Financeiros'},
    'BSCS.SA': {'setor': 'Securitizadoras de Recebíveis'},
    'RBRA.SA': {'setor': 'Securitizadoras de Recebíveis'},
    'PLSC.SA': {'setor': 'Securitizadoras de Recebíveis'},
    'G2DI.SA': {'setor': 'Serviços Financeiros Diversos'},
    'GPIV.SA': {'setor': 'Serviços Financeiros Diversos'},
    'PPLA.SA': {'setor': 'Serviços Financeiros Diversos'},
    'B3SA.SA': {'setor': 'Serviços Financeiros Diversos'},
    'CSUD.SA': {'setor': 'Serviços Financeiros Diversos'},
    'BBSE.SA': {'setor': 'Previdência e Seguros'},
    'CXSE.SA': {'setor': 'Previdência e Seguros'},
    'PSSA.SA': {'setor': 'Previdência e Seguros'},
    'IRBR.SA': {'setor': 'Previdência e Seguros'},
    'WIZC.SA': {'setor': 'Previdência e Seguros'},
    'ALOS.SA': {'setor': 'Exploração de Imóveis'},
    'GSHP.SA': {'setor': 'Exploração de Imóveis'},
    'HBTS.SA': {'setor': 'Exploração de Imóveis'},
    'HBRE.SA': {'setor': 'Exploração de Imóveis'},
    'IGTI.SA': {'setor': 'Exploração de Imóveis'},
    'LOGG.SA': {'setor': 'Exploração de Imóveis'},
    'MNZC.SA': {'setor': 'Exploração de Imóveis'},
    'MULT.SA': {'setor': 'Exploração de Imóveis'},
    'PEAB.SA': {'setor': 'Exploração de Imóveis'},
    'SCAR.SA': {'setor': 'Exploração de Imóveis'},
    'SYNE.SA': {'setor': 'Exploração de Imóveis'},
    'LPSB.SA': {'setor': 'Exploração de Imóveis'},
    'NEXP.SA': {'setor': 'Exploração de Imóveis'},
    'ADMF.SA': {'setor': 'Holdings Diversificadas'},
    'ITSA.SA': {'setor': 'Holdings Diversificadas'},
    'MOAR.SA': {'setor': 'Holdings Diversificadas'},
    'SIMH.SA': {'setor': 'Holdings Diversificadas'},
    'CTBA.SA': {'setor': 'Outros Títulos'},
    'MCRJ.SA': {'setor': 'Outros Títulos'},
    'PMSP.SA': {'setor': 'Outros Títulos'},
    'QVQP.SA': {'setor': 'Outros'},
    'BETP.SA': {'setor': 'Outros'},
    'MAPT.SA': {'setor': 'Outros'},
    'FICT.SA': {'setor': 'Outros'},
    'OPGM.SA': {'setor': 'Outros'},
    'FIGE.SA': {'setor': 'Outros'},
    'PPAR.SA': {'setor': 'Outros'},
    'PRPT.SA': {'setor': 'Outros'},
    'OPSE.SA': {'setor': 'Outros'},
    'OPTS.SA': {'setor': 'Outros'},
}
