MAPA_FIIS = {
    'ABCP11.SA': {'setor': 'Tijolo: Shoppings'},
    'AFCR11.SA': {'setor': 'Papel: Papéis'},
    'AFHI11.SA': {'setor': 'Papel: Papéis'},
    'AFOF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'AGCX11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'AIEC11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'AJFI11.SA': {'setor': 'Sem categoria: Shoppings'},
    'ALMI11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'ALZR11.SA': {'setor': 'Fundo Misto: Misto'},
    'APTO11.SA': {'setor': 'Fundo Misto: Imóveis Residenciais'},
    'APXM11.SA': {'setor': 'Tijolo: Shoppings'},
    'ARCT11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'ARRI11.SA': {'setor': 'Papel: Papéis'},
    'ARXD11.SA': {'setor': 'Papel: Papéis'},
    'ASMT11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'ATCR11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'ATSA11.SA': {'setor': 'Tijolo: Shoppings'},
    'ATWN11.SA': {'setor': 'Fundo Misto: Indefinido'},
    'AURB11.SA': {'setor': 'Tijolo: Imóveis Comerciais - Outros'},
    'BARI11.SA': {'setor': 'Papel: Papéis'},
    'BBFO11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'BBPO11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'BBRC11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'BCFF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'BCIA11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'BCRI11.SA': {'setor': 'Papel: Papéis'},
    'BICR11.SA': {'setor': 'Papel: Papéis'},
    'BLCP11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'BLMC11.SA': {'setor': 'Papel: Papéis'},
    'BLMG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'BLMO11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'BLMR11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'BMII11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'BMLC11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'BNFS11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'BPFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'BPLC11.SA': {'setor': 'Fundo Misto: Misto'},
    'BPML11.SA': {'setor': 'Tijolo: Shoppings'},
    'BRCO11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'BRCR11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'BTAL11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'BTCR11.SA': {'setor': 'Papel: Papéis'},
    'BTLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'BTRA11.SA': {'setor': 'Fundo Misto: Indefinido'},
    'BVAR11.SA': {'setor': 'Tijolo: Varejo'},
    'CACR11.SA': {'setor': 'Papel: Papéis'},
    'CARE11.SA': {'setor': 'Fundo Misto: Misto'},
    'CBOP11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'CCRF11.SA': {'setor': 'Papel: Papéis'},
    'CEOC11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'CJCT11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'CNES11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'CPFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'CPTS11.SA': {'setor': 'Papel: Papéis'},
    'CVBI11.SA': {'setor': 'Papel: Papéis'},
    'CXAG11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'CXCO11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'CXRI11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'CYCR11.SA': {'setor': 'Fundo Misto: Indefinido'},
    'DEVA11.SA': {'setor': 'Papel: Papéis'},
    'DMAC11.SA': {'setor': 'Fundo Misto: Fundo de Desenvolvimento'},
    'DOMC11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'DVFF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'EDGA11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'EURO11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'EVBI11.SA': {'setor': 'Fundo Misto: Misto'},
    'FAED11.SA': {'setor': 'Tijolo: Educacional'},
    'FATN11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'FCFL11.SA': {'setor': 'Tijolo: Educacional'},
    'FEXC11.SA': {'setor': 'Papel: Papéis'},
    'FIGS11.SA': {'setor': 'Tijolo: Shoppings'},
    'FIIB11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'FIVN11.SA': {'setor': 'Tijolo: Shoppings'},
    'FLMA11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'FLRP11.SA': {'setor': 'Tijolo: Shoppings'},
    'FOFT11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'FPAB11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'FVBI11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'FVPQ11.SA': {'setor': 'Tijolo: Shoppings'},
    'GALG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'GAME11.SA': {'setor': 'Fundo Misto: Indefinido'},
    'GARE11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'GCFF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'GCRI11.SA': {'setor': 'Papel: Papéis'},
    'GGRC11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'GSFI11.SA': {'setor': 'Tijolo: Shoppings'},
    'GTLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'GTWR11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'HAAA11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'HABT11.SA': {'setor': 'Papel: Papéis'},
    'HBRH11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'HCTR11.SA': {'setor': 'Papel: Papéis'},
    'HFOF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'HGBS11.SA': {'setor': 'Tijolo: Shoppings'},
    'HGCR11.SA': {'setor': 'Papel: Papéis'},
    'HGFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'HGLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'HGRE11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'HGRU11.SA': {'setor': 'Fundo Misto: Misto'},
    'HLOG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'HPDP11.SA': {'setor': 'Tijolo: Shoppings'},
    'HSML11.SA': {'setor': 'Tijolo: Shoppings'},
    'HSAF11.SA': {'setor': 'Fundo Misto: Indefinido'},
    'HSLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'HSRE11.SA': {'setor': 'Papel: Papéis'},
    'HTMX11.SA': {'setor': 'Tijolo: Hotéis'},
    'IBFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'IRDM11.SA': {'setor': 'Papel: Papéis'},
    'IRIM11.SA': {'setor': 'Papel: Papéis'},
    'ITAI11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'ITIP11.SA': {'setor': 'Papel: Papéis'},
    'ITIT11.SA': {'setor': 'Tijolo: Agências de Bancos'},
    'JASC11.SA': {'setor': 'Tijolo: Shoppings'},
    'JSRE11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'KFOF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'KINV11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'KNCA11.SA': {'setor': 'Papel: Papéis'},
    'KNCB11.SA': {'setor': 'Papel: Papéis'},
    'KNCR11.SA': {'setor': 'Papel: Papéis'},
    'KNHY11.SA': {'setor': 'Papel: Papéis'},
    'KNIP11.SA': {'setor': 'Papel: Papéis'},
    'KNRE11.SA': {'setor': 'Tijolo: Misto'},
    'KNRI11.SA': {'setor': 'Tijolo: Misto'},
    'KNSC11.SA': {'setor': 'Papel: Papéis'},
    'LASC11.SA': {'setor': 'Tijolo: Shoppings'},
    'LGCP11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'LIFE11.SA': {'setor': 'Tijolo: Misto'},
    'LVBI11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'MCCI11.SA': {'setor': 'Papel: Papéis'},
    'MCHF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'MCHY11.SA': {'setor': 'Papel: Papéis'},
    'MCRI11.SA': {'setor': 'Papel: Papéis'},
    'MFII11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'MGCR11.SA': {'setor': 'Papel: Papéis'},
    'MGFF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'MGLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'MORC11.SA': {'setor': 'Papel: Papéis'},
    'MORE11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'MXRF11.SA': {'setor': 'Papel: Papéis'},
    'NAVT11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'NEWL11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'NEWU11.SA': {'setor': 'Tijolo: Imóveis Residenciais'},
    'NPAR11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'NVHO11.SA': {'setor': 'Tijolo: Hotéis'},
    'OUFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'OULG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'OUJP11.SA': {'setor': 'Papel: Papéis'},
    'PABY11.SA': {'setor': 'Tijolo: Imóveis Comerciais - Outros'},
    'PATL11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'PLCR11.SA': {'setor': 'Papel: Papéis'},
    'PLRI11.SA': {'setor': 'Tijolo: Imóveis Residenciais'},
    'PORD11.SA': {'setor': 'Papel: Papéis'},
    'PQDP11.SA': {'setor': 'Tijolo: Shoppings'},
    'PRSV11.SA': {'setor': 'Tijolo: Varejo'},
    'PVBI11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'QAGR11.SA': {'setor': 'Fundo Misto: Misto'},
    'QAMI11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'RBFF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'RBHY11.SA': {'setor': 'Papel: Papéis'},
    'RBRF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'RBRY11.SA': {'setor': 'Papel: Papéis'},
    'RBVA11.SA': {'setor': 'Tijolo: Varejo'},
    'RCFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'RCRB11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'RDES11.SA': {'setor': 'Tijolo: Imóveis Residenciais'},
    'RECR11.SA': {'setor': 'Papel: Papéis'},
    'RECT11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'RFOF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'RIOB11.SA': {'setor': 'Fundo Misto: Misto'},
    'RIZA11.SA': {'setor': 'Fundo Misto: Misto'},
    'RZAG11.SA': {'setor': 'Fundo Misto: Misto'},
    'RZAK11.SA': {'setor': 'Papel: Papéis'},
    'RZTR11.SA': {'setor': 'Fundo Misto: Misto'},
    'SADR11.SA': {'setor': 'Tijolo: Misto'},
    'SARE11.SA': {'setor': 'Fundo Misto: Misto'},
    'SARI11.SA': {'setor': 'Tijolo: Misto'},
    'SEQR11.SA': {'setor': 'Tijolo: Varejo'},
    'SHDP11.SA': {'setor': 'Tijolo: Shoppings'},
    'SHPH11.SA': {'setor': 'Tijolo: Shoppings'},
    'SNCI11.SA': {'setor': 'Papel: Papéis'},
    'SNFF11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'SPXS11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'SPTW11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'TEKA11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'TEPP11.SA': {'setor': 'Papel: Papéis'},
    'TGAR11.SA': {'setor': 'Fundo Misto: Fundo de Desenvolvimento'},
    'TORD11.SA': {'setor': 'Fundo Misto: Misto'},
    'TRBL11.SA': {'setor': 'Tijolo: Varejo'},
    'TRXB11.SA': {'setor': 'Tijolo: Varejo'},
    'TRXF11.SA': {'setor': 'Tijolo: Varejo'},
    'URPR11.SA': {'setor': 'Papel: Papéis'},
    'VCJR11.SA': {'setor': 'Papel: Papéis'},
    'VCRR11.SA': {'setor': 'Papel: Papéis'},
    'VGHF11.SA': {'setor': 'Papel: Papéis'},
    'VGIA11.SA': {'setor': 'Fundo Misto: Misto'},
    'VGIP11.SA': {'setor': 'Papel: Papéis'},
    'VGIR11.SA': {'setor': 'Papel: Papéis'},
    'VIFI11.SA': {'setor': 'Fundo de Fundos: Fundo de Fundos'},
    'VILG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'VINO11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'VISC11.SA': {'setor': 'Tijolo: Shoppings'},
    'VIUR11.SA': {'setor': 'Papel: Papéis'},
    'VRTA11.SA': {'setor': 'Papel: Papéis'},
    'VSLH11.SA': {'setor': 'Papel: Papéis'},
    'WHGR11.SA': {'setor': 'Fundo Misto: Misto'},
    'WPLZ11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'XPCI11.SA': {'setor': 'Papel: Papéis'},
    'XPIN11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'XPLG11.SA': {'setor': 'Tijolo: Imóveis Industriais e Logísticos'},
    'XPML11.SA': {'setor': 'Tijolo: Shoppings'},
    'XPPR11.SA': {'setor': 'Tijolo: Lajes Corporativas'},
    'XPSF11.SA': {'setor': 'Papel: Fundo de Fundos'},
    'XTED11.SA': {'setor': 'Tijolo: Educacional'},
}