[build]
  publish = "."

[[redirects]]
  from = "/ativacao/*"
  to = "/ativacao_netlify.html"
  status = 200

[[redirects]]
  from = "/ativar/*"
  to = "/ativacao_netlify.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"