services:
  - type: web
    name: ponto-otimo-invest
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neon-db
          property: connectionString
      - key: GMAIL_EMAIL
        value: pontootimoinvest@gmail.com
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RENDER_APP_URL
        value: https://ponto-otimo-invest.onrender.com
      - key: RAILWAY_APP_URL
        value: https://web-production-040d1.up.railway.app