name: Atualização Diária de Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest


    # Damos permissão ao robô para escrever no repositório
    permissions:
      contents: write
    # ---------------------------

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
   
      - name: Instalar Dependências
        run: |
          pip install yfinance pandas requests python-bcb html5lib lxml numpy investpy

      - name: Executar Pipeline de Coleta de Dados
        run: |
          python pipeline_dados.py

      - name: Commit dos Arquivos de Dados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dados/
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualização automática dos dados históricos"
          
      - name: Push das Alterações
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
